name: Create Manylinux Wheels
on:
  push:
    tags:
      - v*

jobs:
  manylinux-wheels:
    runs-on: ubuntu-latest
    name: Create the manylinux wheels for all supported Python versions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -f Dockerfile.manylinux . -t pyceres-manylinux:latest
      - name: Copy wheels
        run: |
          mkdir /wheels
          docker run --rm --name pyceres-manylinux -v /wheels:/external pyceres-manylinux:latest
      - name: Upload to Release
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /wheels/pyceres-wheels/pyceres*.whl
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: "Manylinux Wheels"


